# Generated by Django 3.2.10 on 2021-12-16 23:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211216_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='row_seats',
            field=models.IntegerField(default=0, verbose_name='Seats per row'),
        ),
        migrations.AlterField(
            model_name='building',
            name='section_rows',
            field=models.IntegerField(default=0, verbose_name='Rows of per section'),
        ),
        migrations.AlterField(
            model_name='building',
            name='sections',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField(default=datetime.datetime(2021, 12, 16, 23, 47, 43, 433216))),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not paid'), ('canceled', 'Cancelled')], default='not paid', max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ticket')),
            ],
        ),
    ]
