# Generated by Django 3.2.10 on 2021-12-16 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_reservation_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 23, 58, 16, 509094)),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='ticket',
        ),
        migrations.AddField(
            model_name='reservation',
            name='ticket',
            field=models.ManyToManyField(to='api.Ticket'),
        ),
    ]
