# Generated by Django 3.2.10 on 2021-12-17 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_reservation_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_option',
            field=models.CharField(choices=[('even', 'Even'), ('all together', 'All together'), ('avoid one', 'Avoid one')], default='avoid one', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 0, 17, 51, 202175)),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='ticket',
        ),
        migrations.AddField(
            model_name='reservation',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.ticket'),
        ),
    ]
