# Generated by Django 3.2.10 on 2021-12-17 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211217_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='seat',
            name='section',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 14, 6, 47, 531208)),
        ),
    ]
