# Generated by Django 3.2.10 on 2021-12-18 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_reservation_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='ticket_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 2, 4, 30, 409386)),
        ),
    ]
