# Generated by Django 3.2.10 on 2021-12-18 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_reservation_expiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='available',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('selected', 'Selected')], default='available', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 11, 40, 28, 11052)),
        ),
    ]
