# Generated by Django 3.2.10 on 2021-12-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20211218_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
