# Generated by Django 3.2.10 on 2021-12-18 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_reservation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
