# Generated by Django 3.2.10 on 2021-12-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_ticketreservation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_option',
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reservation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='selling_option',
            field=models.CharField(choices=[('even', 'Even'), ('all together', 'All together'), ('avoid one', 'Avoid one')], default='avoid one', max_length=100),
        ),
        migrations.AddField(
            model_name='ticketset',
            name='selling_option',
            field=models.CharField(choices=[('even', 'Even'), ('all together', 'All together'), ('avoid one', 'Avoid one')], default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='TicketReservation',
        ),
    ]
