# Generated by Django 3.2.10 on 2021-12-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20211218_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketset',
            name='selling_option',
            field=models.CharField(blank=True, choices=[('even', 'Even'), ('all together', 'All together'), ('avoid one', 'Avoid one')], max_length=100, null=True),
        ),
    ]
