# Generated by Django 3.2.10 on 2021-12-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_ticketset_selling_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketset',
            name='selling_option',
            field=models.CharField(choices=[('even', 'Even'), ('all together', 'All together'), ('avoid one', 'Avoid one')], default=None, max_length=100),
        ),
    ]
