# Generated by Django 3.2.10 on 2021-12-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_ticketset_selling_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reservation'),
        ),
        migrations.AlterField(
            model_name='ticketset',
            name='selling_option',
            field=models.CharField(blank=True, choices=[('even', 'Even'), ('all together', 'All together'), ('avoid one', 'Avoid one')], max_length=100, null=True),
        ),
    ]
