# Generated by Django 3.2.10 on 2021-12-19 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20211219_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='ticket_assigned',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seat'),
        ),
    ]
