# Generated by Django 3.2.10 on 2021-12-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20211219_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='selling_option',
            field=models.CharField(blank=True, choices=[('even', 'Even'), ('all together', 'All together'), ('avoid one', 'Avoid one')], max_length=100, null=True),
        ),
    ]
