# Generated by Django 3.2.10 on 2021-12-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
    ]
