# Generated by Django 3.2.10 on 2021-12-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
