# Generated by Django 3.2.10 on 2021-12-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_reservation_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
